services:
  music-link-filler:
    build:
      context: .
    image: music-link-filler-cloud-hybrid:latest
    container_name: music-link-filler-cloud-hybrid
    ports:
      - "5280:5280"
    environment:
      PORT: "5280"
    restart: unless-stopped
